### ISSUE TITLE
cudaCheckError() failed3 : invalid configuration argument

### ISSUE THREAD

**Issue by QiyuLuo** [Amgao/RLS-RTMDNet#6]
I compiled **roi_align** using `Python setup.py develop`.
CudaCheckError () error occurred while running Run.py. 
My environment is Torch1.2, cuda10.0.
How to solve this problem? Is the way I compile wrong?
Looking forward to your early reply. Thank you.

**Comment by Amgao** [comment]
Would you please try this command: python setup.py build -> make -C src/cuda -> make -C src/cuda clean

**Comment by QiyuLuo** [comment]
Did you upload the roi_align file incorrectly? When i run **make** command, the following error occurred.
```python
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Makefile:2: recipe for target 'all' failed
```
I think this is an old version torch. After I fixed this bug, another one happened, and I didn't know what to do.

```python
  File "build.py", line 32, in <module>
    extra_objects=extra_objects
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 233, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/setuptools/__init__.py", line 163, in __init__
    _Command.__init__(self, dist)
  File "/opt/conda/lib/python3.6/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
TypeError: dist must be a Distribution instance
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

```
